# Site settings
title: "w3craft"
description: > # this means to ignore newlines until "baseurl:"
 Напишите потрясающее описание для вашего нового сайта здесь. Вы можете отредактировать это 
  описание в _config.yml. Оно появится в вашем документе Meta (для
  Результатов поиска Yandex) и в описании сайта Feed.xml.
