# Site settings
title: "w3craft"
description: > # this means to ignore newlines until "baseurl:"
 Напишите потрясающее описание для вашего нового сайта здесь. Вы можете отредактировать это 
  описание в _config.yml. Оно появится в вашем документе Meta (для
  Результатов поиска Yandex) и в описании сайта Feed.xml.

github_username: EvilPencil

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      
baseurl: "" # the subpath of your site, e.g. /w3craft
url: "https://w3craft.ru" # базовое имя хоста и протокол для вашего сайта, например, http://example.com

plugins:
  - "jekyll-sitemap"
  - "jekyll-feed"
  - "jekyll-seo-tag"
